### ISSUE TITLE
Better Code Hub web hook 

### ISSUE THREAD

**Issue by MichielCuijpers** [arhix/cicd-buzz#1]
Hi @arhix thanks for forking cicd-buzz of my colleague Rob van der Leek. I noticed in our logs that the Better Code Hub stopped analyzing cicd-buzz. 

The reason is that we do not yet support changing the (casing of the ) owner / repo name. 

Please re-toggle the Push and Pull request button, Better Code Hub will work again.

![schermafbeelding 2017-06-10 om 20 19 02](https://user-images.githubusercontent.com/18576001/27435850-a58b1396-575d-11e7-9076-7a9f0db22c6f.jpg)

Best Regards 

Michiel Cuijpers

**Comment by arhix** [comment]
Hello @MichielCuijpers, thank you for your attention.
I re-switched the Push and Pull request button, but the analysis was failed.
Maybe you have any ideas, how I can fix it?

**Comment by MichielCuijpers** [comment]
Hi @arhix the casing name change triggers some strange things. Will need to look into this. Could make a new fork and name it arhix/cicd-buzz-2?

**Comment by MichielCuijpers** [comment]
Hi @arhix we did some maintenance work on our side, you could try to run Better Code Hub again?

**Comment by arhix** [comment]
Hello @MichielCuijpers, I still get an analysis error.

**Comment by MichielCuijpers** [comment]
That is strange, could you send a screen shot the error on the BetterCodeHub.com repositories page after you clicked the play button?

**Comment by arhix** [comment]
It's works now. Thanks for your help
